CreateWiki.php

We must declare new permissions otherwise they are not available to other extensions, mainly CentralAuth

Declare new permissions so they are available to CentralAuth

---

i18n/en.json

Currently is meta specific. Updating as the log is used on all wikis now. Wiki Creations and requests only happen on meta. We can customise it on meta directly.

Update farmer log description

---

SpecialRequestWikiQueue.php

It's redundant, and I'm pretty sure we're using the wrong format option.

remove use of wfTimestamp

---

CreateWiki.hooks.php
extension.json

Reason is in mw 1.31 you cannot specify this config in other extensions otherwise it fails with a hard failure.

Move wgCreateWikiDatabase config to callback

---

includes/RequestWiki/RequestWikiRequestViewer.php

This fixes an issue where a request is not found, but instead of returning an empty array, it returned false, which caused an issue in HTMLForm.php.

Return an empty array instead of false in getFormDescriptor

---

includes/WikiManager.php

it's the default under mysql 5.5+ and MariaDB 10.2+.
Users can set innodb to be the default in the configuration. (which should be preferred).
Bug: T4611

wikimanager: Stop setting storage_engine to innodb

---

includes/RequestWiki/RequestWikiRequestViewer.php

Having duplicate $user variables was interfering in checking if the user was allowed the defined permission.
We fix this by renaming one of the variables to $userR which stands for the user from the request, where as the other one is from the db.

Fix getting the user

---

includes/CreateWikiJson.php

This creates .tmp files first and renames aftwards to drop the .tmp prefix.

Fix race conditions when updating .json files

---

extension.json
includes/WikiManager.php

This is so system administrators can set the collation for the database, for example "DEFAULT SET utf8mb4 COLLATE utf8mb4_unicode_ci".

Add new wgCreateWikiCollation config

---

includes/WikiManager.php

The jobrunner has a timeout so we don't really need these set.

WM->create: Set time and walltime to 0 for scripts

---

extension.json
includes/RequestWiki/SpecialRequestWiki.php

So it's easier to add new regex blacklists, and doesn't have one huge string. Feel free to close this if it isn't a good idea to do though.

Allow $wgCreateWikiBlacklistedSubdomains to be an array

---

includes/RequestWiki/WikiRequest.php

Changes the behavior from 06a282b, which completely removed the declined notifications type from sending, this in turn, remains to keep it from sending 2 notifications for declined requests while still supporting the `request-declined` type.
Additionally, Currently, it seems like echo does not send *any* email notifications for declined requests or request comments (reliably) - regardless of email preferences set in Special:Preferences, which is something else that needs looked into also. It does still send web notifications though, but even for declined notifications, it sends that it received a comment, not that it was declined, which is what this fixes.

Re-add echo notifications for declined requests

---

i18n/en.json
includes/CreateWiki/SpecialCreateWiki.php
includes/RequestWiki/RequestWikiRequestViewer.php
includes/RequestWiki/SpecialRequestWiki.php
includes/RequestWiki/WikiRequest.php

This has been mentioned multiple times so doing this. It also adds a help message to the reason field.
Also makes it so you can't post an empty comment or open a wiki request with a completely empty reason (or contains only whitespace or newlines)

Use textarea type for reason and comment fields

---

includes/WikiInitialise.php

* miraheze/mw-config#3991 adds implementation for this.
**Notes:**
* To enable automatic loading of extensions, `$wi->loadExtensions()` will be needed in LocalSettings.php.
* This does not support extensions loaded through a PHP entrypoint.
* Extensions can still be disabled by adding their **ExtensionRegistry** name to the `$wi->disabledExtensions` array in LocalSettings.php.

Support loading extension/skin entry points automatically

---

includes/RequestWiki/RequestWikiAIJob.php

We don't want the regex to have to match exactly, but rather contained within.

Fix regex for checking the AI approval blacklist

---

.github/workflows/mediawiki-tests.yml
extension.json
includes/CreateWikiJson.php

```ps
9.43% 76.251      3 - Wikimedia\Rdbms\Database::initConnection
9.43% 76.227      3 - Wikimedia\Rdbms\Database::doInitConnection
9.43% 76.213      3 - Wikimedia\Rdbms\DatabaseMysqlBase::open
9.38% 75.809     25 - Wikimedia\Rdbms\LoadBalancer::getMaintenanceConnectionRef
9.22% 74.534     17 - wfGetDB
9.06% 73.193      1 - MediaWiki\HookContainer\HookRunner::onSetupAfterCache
9.04% 73.094      1 - CreateWikiHooks::onSetupAfterCache
9.00% 72.732     34 - Wikimedia\Services\ServiceContainer::{closure}
8.80% 71.090      1 - CreateWikiJson::__construct
```
Afterwords, I can't even find that in profile. Additionally, there is currently a lot of logs within Graylog, relating to DB connection errors, with CreateWikiJson, and CreateWikiHooks, this would hopefully prevent them:
```ps
Cannot …
```

[Performance] only connect to database if actually used in CreateWikiJson

---

includes/WikiManager.php
tests/phpunit/WikiManagerTest.php

Messed up logic. If the wiki is marked as deleted, it always fails to run WikiManager::delete.

Fix WikiManager::delete

---

includes/CreateWikiJson.php

Should allow adding additional database lists or modify existing ones. This is primarily to support adding database lists for beta.
Example of what we should be able to do to achieve this, if I did this PR correctly:
```php
public static function onCreateWikiJsonGenerateDatabaseList( &$databaseLists ) {
$dbr = wfGetDB( DB_REPLICA, [], 'testglobal' );
$allBetaWikis = $dbr->select(
'cw_wikis',
[
'wiki_dbcluster',
'wiki_dbname',
'wiki_deleted',
'wiki_url',
'wiki_sitename'
]
);
$combiList = [];
$deletedList = [];
foreach ( $allBetaWikis as $wiki ) {
if ( $wiki->wiki_deleted == 1 ) {
$deletedList[$wiki->wiki_dbname] = [
's' => $wiki->wiki_sitename,
'c' => $wiki->wiki_dbcluster
];
} else {
$combiList[$wiki->wiki_dbname] = [
's' => $wiki->wiki_sitename,
'c' => $wiki->wiki_dbcluster
];
if ( …
```

Add hook to support modifying available database lists

---

.github/workflows/mediawiki-tests.yml
includes/CreateWikiRegexConstraint.php
includes/RequestWiki/RequestWikiAIJob.php
includes/RequestWiki/SpecialRequestWiki.php
includes/RequestWiki/WikiRequest.php

* Add regex validation and sanitisation
* Avoid failing the entire regex if one line or array key is invalid, rather just skip it and log in debug log that something went wrong
* Improve on-wiki comment disallowed words message regex — don't pull from `Title::newFromText()`, but rather `wfMessage()` directly
* Centralised regex functions
Also deprecates `MediaWiki:CreateWiki-blacklist`, replacing it with `MediaWiki:CreateWiki-disallowlist`, temporally maintaining current as fallback to allow for time for transition.

Create new CreateWikiRegexConstraint class

---

includes/Hooks/CreateWikiHookRunner.php
includes/Hooks/CreateWikiReadPersistentModelHook.php
includes/Hooks/CreateWikiWritePersistentModelHook.php
includes/RequestWiki/RequestWikiAIJob.php
includes/RequestWiki/WikiRequest.php
maintenance/createPersistentModel.php

We can potentially use something similar to this for compatibility with Swift:
```php
use MediaWiki\MediaWikiServices;
public static function onCreateWikiReadPersistentModel( &$pipeline ) {
$backend = MediaWikiServices::getInstance()->getFileBackendGroup()->get( 'swift-backend' );
if ( $backend->fileExists( [ 'src' => $backend->getContainerStoragePath( 'createwiki-persistent-model' ) . '/requestmodel.phpml' ] ) ) {
$pipeline = unserialize(
$backend->getFileContents( [
'src' => $backend->getContainerStoragePath( 'createwiki-persistent-model' ) . '/requestmodel.phpml',
] )
);
}
}
public static function onCreateWikiWritePersistentModel( $pipeline ) {
$backend = MediaWikiServices::getInstance()->getFileBackendGroup()->get( 'swift-backend' );
$backend->prepare( [ 'dir' => …
```

Add hooks for reading and writing persistent model

---

extension.json
includes/RemoteWiki.php
includes/WikiManager.php
tests/phpunit/RemoteWikiTest.php
tests/phpunit/WikiManagerTest.php

Doing here rather than using the hooks, as in this instance, may not be Miraheze-specific and should always ensure that/
Also adds `$wgCreateWikiUseSecureContainers` and `$wgCreateWikiExtraSecuredContainers` configs.

Make sure local zones are created and secure when necessary

---

includes/WikiManager.php

this ensures that if the cwdb writer gets stuck into a transaction, that transaction will be finished before the scripts get called

use DeferredUpdates for shell scripts

---

includes/WikiManager.php

this will ensure that even if another process triggers CreateWikiJson::update at the same time (causing a race condition to updating the databases.json list), the changes to cw_wikis will be committed and available to all processes that might be affected by this race condition.

delay recacheJson to DeferredUpdates

---

i18n/en.json
includes/RequestWiki/SpecialRequestWikiQueue.php

This PR adds a link from wiki requests back to the wiki request queue, akin to how subpages have a link under them which links back to the main page. Useful for requesters and for WCs to quickly go back to the queue.

Add link from wiki request back to queue

---

includes/RequestWiki/RequestWikiRequestViewer.php

If a user with `createwiki` is blocked, they cannot access CreateWiki or RequestWiki but they can still create wikis. This doesn't make much sense as if a user is blocked, it's for a reason so this patches that logic flaw.

Do not show creation form if blocked

---

includes/RequestWiki/RequestWikiRequestViewer.php
includes/RequestWiki/SpecialRequestWiki.php

If the category, private, purpose, and bio features are turned off, these values will be missing from the form data. As the DB does not accept NULL for these values, we must fall back to a zero value.

RequestWiki use zero instead of null if values missing

---

i18n/en.json

Plural "wikis" doesn't need an apostrophe.

Remove an unnecessary apostrophe from a message

---

tests/phpunit/RemoteWikiTest.php
tests/phpunit/SpecialRequestWikiTest.php
tests/phpunit/WikiManagerTest.php

Thanks to wikimedia/mediawiki@71ff052 tables are automatically cleared after each test on 1.42, unless they are manipulated in some way in `addDBDataOnce()`.

Fix tests for 1.42

---

includes/RequestWiki/RequestWikiRequestViewer.php

This change is to prevent wiki requests from being approved by mistake

Make on hold the first option when handling wiki requests

---

extension.json
includes/Hooks.php

Exposes the canned responses as a variable on subpages of Special:RequestWikiQueue.
https://issue-tracker.miraheze.org/T10683

T10683: Expose the canned responses to JavaScript

---

extension.json
includes/RequestWiki/Handler/RestWikiRequest.php

This handler will also be used for handling wiki requests and filing new wiki requests in the future

Rename query_wiki_request to wiki_request

---

includes/RequestWiki/Handler/RestWikiRequest.php
includes/RequestWiki/RequestWikiRequestViewer.php

Unnecessary checks, since if the user doesn't have this perm it should not be able to reach the special pages or APIs to begin with.

Remove checks for `(read)`

---

includes/RequestWiki/RequestWikiRequestViewer.php

This code was responsible for https://issue-tracker.miraheze.org/T11993, CVE-2024-29883.
Once that was fixed this line became useless, but was never removed.

Drop old code

---

includes/RequestWiki/WikiRequest.php

Everything from the database is stored by MediaWiki as a string. A string will never be === to an int, preventing this check from working

Fix comparison between requested and current suppression level

---

i18n/en.json

It doesn't really need to be there, and none of the other ones have the colon:

Remove colon from the database name header

---

modules/ext.createwiki.oouiform.ooui.less

Breaks the form element. Whatever reason this was originally here for probably no longer applies.
It appears a change to the OOUI elements makes it so that the top property is not automatically generated for the element if it already has one custom applied.
Bug: T12265

remove top from oo-ui-menuSelectWidget

---

i18n/en.json
includes/RequestWiki/SpecialRequestWiki.php

Currently, it's just a browser-side warning but a server-side check would be useful.

Require agreement checkbox to be checked if defined

---

includes/Services/WikiRequestManager.php

Since sendNotifications can be a UserIdentity but getRequester and user from comments are User (as UserFactory returns) we need to make sure we usd an array_diff on User not any UserIdentity, so we do newFromUserIdentity.

T12726: Fix not sending notifications to actor

---

i18n/en.json
i18n/qqq.json
includes/Exceptions/MissingWikiError.php
includes/Services/RemoteWikiFactory.php

If we don't throw anywhere like before #567, then we now get something like `Error: Typed property Miraheze\CreateWiki\Services\RemoteWikiFactory::$locked must not be accessed before initialization`, so we need to throw an error, but also, like before, we want it to be a nice user-friendly message, so we do a custom exception that extends `ErrorPageError` and shows the error in a nice errorBox.

Add MissingWikiError exception

---

includes/RequestWiki/RequestWikiQueuePager.php

* Also fixes sorting by timestamp so it correctly goes old to new or vice versa.

RequestWikiQueuePager: Use timestamp for default sort

---

includes/Services/WikiRequestManager.php

1) This shouldn't need it, it runs on the DB and just uses it for comments etc... shouldn't actually need the (system) account to see this.
2) Even if it doesn't work for hidden requests without it, we don't need to run this (and shouldn't) on suppressed requests anyway.

Remove CreateWiki AI from all isVisibilityAllowed

---

includes/RequestWiki/RequestWikiQueuePager.php

Reported on the Miraheze Community Roles Discord server: <https://discord.com/channels/1006797886027214949/1225518258451517492/1344271653915332641>
Exception message and relevant stacktrace:
```
[5e07db8fea2c2e887869264a] /wiki/Special:RequestWikiQueue?dbname=&language=*&requester=&status=declined   TypeError: Miraheze\CreateWiki\RequestWiki\RequestWikiQueuePager::escape(): Argument #1 ($value) must be of type string, null given, called in /srv/mediawiki/1.43/extensions/CreateWiki/includes/RequestWiki/RequestWikiQueuePager.php on line 64
from /srv/mediawiki/1.43/extensions/CreateWiki/includes/RequestWiki/RequestWikiQueuePager.php(97) 0 /srv/mediawiki/1.43/extensions/CreateWiki/includes/RequestWiki/RequestWikiQueuePager.php(64): Miraheze\CreateWiki\RequestWiki\RequestWikiQueuePager->escape( …
```

Fix escaping NULL database records

---

includes/Exceptions/MissingWikiError.php
includes/Services/CreateWikiDataFactory.php
includes/Services/RemoteWikiFactory.php

Improves type hinting (ensuring wiki is a string) and reduces duplication (don't have to manually have to keep passing the same message key)

Only pass wiki to MissingWikiError

---

maintenance/renameWiki.php

Already runs in WikiManagerFactory::rename(), we don't need to have it run twice.

Don't run onCreateWikiRename in maintenance script

---

maintenance/CheckLastWikiActivity.php

Improves performance by about 898 times(!) according to profiling I did:
```shell
stdClass Object
(
[Query_ID] => 1
[Duration] => 1.00628092
[Query] => SELECT /* MwSql::sqlDoQuery  */ MAX(log_timestamp) FROM logging WHERE log_type != 'renameuser' AND log_type != 'newusers'
)
stdClass Object
(
[Query_ID] => 2
[Duration] => 0.00112031
[Query] => SELECT /* MwSql::sqlDoQuery  */ log_timestamp FROM logging WHERE log_type != 'renameuser' AND log_type != 'newusers' ORDER BY log_timestamp DESC LIMIT 1
)
```
1.00628092s -> 0.00112031s

Optimize CheckLastWikiActivity

---

maintenance/RenameWiki.php

This makes it more clear what it will actually do so you don't do wrong orders etc...

RenameWiki: use named options rather than positional arguments

---

includes/ConfigModuleInterface.php
includes/IConfigModule.php
includes/Services/RemoteWikiFactory.php
tests/phpunit/Services/RemoteWikiFactoryTest.php

Can be used for all the ManageWiki module helpers as well, which all of those, along with RemoteWikiFactory require some common methods to be implemented, so we make an interface to do that.

Add an interface for config modules

---

includes/Helpers/RemoteWiki.php
includes/Hooks/CreateWikiHookRunner.php
includes/Hooks/CreateWikiRemoteWikiCommitHook.php

This is a temporary hook during the migration of ManageWiki cache from CreateWiki to ManageWiki. After that is completed, the ManageWikiCoreProvider hook will be updated to pass DataStoreFactory as well, so that any providers can access it and reset the cache themselves when changes are committed or when needed.

Add new CreateWikiRemoteWikiCommit hook

---

includes/Notifications/EchoRequestMoreDetailsPresentationModel.php

This fixes a regression introduced in fd12cecebdc6208e02d4da8a6279e5dc18ce2ab3.
Follow-up to 0b6468a
```
MessageCache::parseWithPostprocessing(): Argument #1 ($text) must be of type string, null given, called in /srv/mediawiki/1.44/extensions/Echo/includes/DiscussionParser.php on line 1279
from /srv/mediawiki/1.44/includes/language/MessageCache.php(1434)
#0 /srv/mediawiki/1.44/extensions/Echo/includes/DiscussionParser.php(1279): MessageCache->parseWithPostprocessing(null, MediaWiki\Page\PageReferenceValue, bool, bool, LanguageEn)
#1 /srv/mediawiki/1.44/extensions/CreateWiki/includes/Notifications/EchoRequestMoreDetailsPresentationModel.php(25): MediaWiki\Extension\Notifications\DiscussionParser::getTextSnippet(null, LanguageEn)
#2 …
```

Use 'reason' param if 'comment' is unset in RequestMoreDetails notification
