- SpecialCreateWiki.php
logging issue + not relevant information. Main Page exists, woo, who cares if RC shows it.
> Suppress RC logs for Main Page

- SpecialRequestWikiEdit.php
not too sure of the logic on line 128 tho
> convert private to a checkbox

- SpecialRequestWikiEdit.php
> also modify cw_dbname

- SpecialRequestWiki.php
This re adds the subdomain check. This makes sure it does not contain spaces.
> Re add subdomain check

- SpecialRequestWiki.php
Part of this prevented the reason from being placed in the farmer log as before
> $comment -> $reason

- SpecialRequestWikiEdit.php
temporary while I write up a better solution
> don't show submit button if disabled

- includes/RequestWiki/SpecialRequestWiki.php
move strtolower earlier
account for users entering the $wgCreateWikiSubdomain as a part of their subdomain without throwing an error
> adjustments to handling subdomain

- includes/RequestWiki/RequestWikiQueuePager.php
additional restraint on createwiki level visibility
> hide deleted requests from pager

- includes/RequestWiki/RequestWikiRequestViewer.php
makes the most sense out of the existing system messages
> change success message

- includes/RequestWiki/RequestWikiRequestViewer.php
- includes/RequestWiki/SpecialRequestWikiEdit.php
- includes/RequestWiki/SpecialRequestWikiQueue.php
See https://phabricator.wikimedia.org/T243371
> Remove use of global $wgUser

- includes/WikiInitialise.php
This is mainly for the jobrunner.
> Set a default for wgServer - fallback incase wgServer is not set

- includes/RequestWiki/RequestWikiQueuePager.php
- includes/RequestWiki/RequestWikiRequestViewer.php
- includes/RequestWiki/SpecialRequestWikiEdit.php
> Replace deprecated isAllowed(...) with userHasRight(...)

- includes/CreateWikiHooks.php
modifyField -> modifyExtensionField
modifyTable -> modifyExtensionTable
Bug: T5393
> Switch some methods in fnCreateWikiSchemaUpdates

- includes/RequestWiki/SpecialRequestWikiEdit.php
It's no longer set, so we temporarily set this to an empty string like
https://github.com/miraheze/CreateWiki/blob/89fd8c45f019308f16b43f8fa9b4ac1121dccb35/includes/RequestWiki/SpecialRequestWiki.php#L144
> Fix 'customdomain'

- includes/CreateWikiJson.php
> Make sure file write is succeeded before renaming

- includes/WikiManager.php
> Don't need to open wfGetDB twice

- includes/CreateWikiHooks.php
- sql/cw_comments.sql
- sql/patches/patch-cw_comments-text.sql
- sql/patches/patch-cw_comments-varchar-increase.sql
This ups the maximum characters from 512 to 2000.
Bug: T5898
> Increase cw_comments.cw_comment varcher column to 2000

- includes/WikiInitialise.php
> Make sure wgContentNamespaces is an int

- maintenance/changeDBCluster.php
- maintenance/changeDbCluster.php
Allows you to update multiple wikis and set their db cluster to a different value.
> Add a ChangeDBCluster script

- includes/CreateWikiJson.php
- includes/WikiInitialise.php
> Fix wikis being deleted

- maintenance/manageInactiveWikis.php
> Check that the value received from checkLastWikiActivity returns a number

- includes/RequestWiki/SpecialRequestWiki.php
https://github.com/wikimedia/mediawiki/blob/5a2f573ab52a4920876d58dd3720c8985679d97c/includes/user/User.php#L3075
> Use User::isRegistered instead of User::isLoggedIn

- includes/RequestWiki/SpecialRequestWiki.php
Fixes potential "Deprecated: Non-static method SpecialRequestWiki::isValidReason() should not be called statically"
> [BUG FIX] fix potential "deprecated" notice

- extension.json
- includes/RemoteWiki.php
- includes/RequestWiki/WikiRequest.php
- includes/WikiManager.php
- maintenance/DBListGenerator.php
- maintenance/deleteWikis.php
- maintenance/manageInactiveWikis.php
- maintenance/migrateServerName.php
- maintenance/populateWikiCreation.php
- maintenance/renameWiki.php
DB_MASTER is renamed to DB_PRIMARY on 1.36
> DB_MASTER -> DB_PRIMARY

- includes/WikiInitialise.php
If this doesn't work then the entire change in mw-config at least should be reverted.
> Cache extension list instead of loading each page load

- includes/CreateWikiHooks.php
* Should be deployed at the same time as miraheze/mw-config#4126.
> Don't set `$wgConf` from SetupAfterCache

- includes/RequestWiki/WikiRequest.php
Uses the comment notification for other involved users.
> Fix notification for other involved users when request is declined

- includes/RequestWiki/RequestWikiRequestViewer.php
> Use selectorother type for canned responses to support custom

- .phan/config.php
The original words from https://github.com/miraheze/CreateWiki/pull/283#discussion_r794250715
> doc: Add why suppress_issue_types is specified

- maintenance/DBListGenerator.php
Reverts miraheze/CreateWiki#247
> Revert "Delete DBListGenerator.php"

- package-lock.json
- package.json
Reverts miraheze/CreateWiki#296
> Revert "Bump stylelint-config-wikimedia from 0.11.1 to 0.12.1"

- includes/RequestWiki/RequestWikiRequestViewer.php
- includes/RequestWiki/SpecialRequestWikiQueue.php
> make addModules an array

- maintenance/checkLastWikiActivity.php
- maintenance/deleteWikis.php
- maintenance/generateMissingCache.php
- maintenance/listDatabases.php
- maintenance/manageInactiveWikis.php
- maintenance/populateMainPage.php
- maintenance/populateWikiCreation.php
- maintenance/rebuildExtensionListCache.php
- maintenance/renameWiki.php
> Don't use Maintenance::$mDescription directly

- extension.json
- i18n/en.json
- includes/RequestWiki/WikiRequest.php
> Make setting a request on hold generate a log action

- maintenance/populateWikiCreation.php
> populateWikiCreation: replace selectDB with selectDomain

- maintenance/checkLastWikiActivity.php
- maintenance/createPersistentModel.php
- maintenance/deleteWikis.php
- maintenance/manageInactiveWikis.php
- maintenance/migrateServerName.php
- maintenance/populateWikiCreation.php
- maintenance/renameWiki.php
> maintenance: replace usages of wfGetDB

- includes/RequestWiki/RequestWikiRequestViewer.php
So that onhold may still be used.
> T9815: only disallow approving request if invalid database

- includes/WikiManager.php
No guarantees a page with ID 1 will exist.
> WikiManager: use `Title::newMainPage()` instead of `newFromId()`

- includes/CreateWikiJson.php
- includes/Hooks.php
- includes/RemoteWiki.php
- includes/WikiInitialise.php
- tests/phpunit/RemoteWikiTest.php
It should definitely properly support the default values for these configs...
> Support checking configs for states

- includes/WikiManager.php
> Remove extra whitespace

- extension.json
- includes/CreateWiki/CreateWikiLogFormatter.php
- includes/RequestWiki/WikiRequest.php
This will prevent raw html tags from showing up in IRC feeds, basically every other extension respects this parameter
> Logging: respect $this->plaintext

- extension.json
- includes/CreateWiki/CreateWikiLogFormatter.php
- includes/RequestWiki/WikiRequest.php
Reverts miraheze/CreateWiki#409
> Revert "Logging: respect $this->plaintext"

- includes/RemoteWiki.php
- maintenance/setContainersAccess.php
- tests/phpunit/RemoteWikiTest.php
- tests/phpunit/WikiManagerTest.php
Remove use of CreateWikiUseSecureContainers
> Remove use of CreateWikiUseSecureContainers

- extension.json
- includes/CreateWiki/CreateWikiLogFormatter.php
- includes/RequestWiki/WikiRequest.php
This reverts commit c08666a3adafe8fe16e069921c73dba8117addcd.
Reverting the revert, as I'm pretty sure the alternative solution won't get worked on.
> Revert "Revert "Logging: respect $this->plaintext" (#410)"

- includes/WikiManager.php
> Revert "Return FatalError if trying to delet a wiki that does not exist"

- includes/RequestWiki/Handler/RestWikiRequest.php
Adds localized error messages. I also did some misc cleanup
> Cleanup RestWikiRequest

- extension.json
- i18n/en.json
- i18n/qqq.json
- includes/RequestWiki/Handler/RestWikiRequestsByUser.php
This REST endpoint allows getting a list of all wiki requests made by an user. It also returns the suppression level
> Add RestWikiRequestsByUser

- includes/RequestWiki/Handler/RestWikiRequest.php
- includes/RequestWiki/Handler/RestWikiRequestsByUser.php
This PR casts `bio` from RestWikiRequest to `bool` and `id` from `RestWikiRequestsByUser` to `int`.
> REST: Cast some data to appropiate types

- includes/CreateWiki/SpecialCreateWiki.php
- includes/EntryPointUtils.php
- includes/Hooks.php
- includes/RequestWiki/Handler/RestWikiRequest.php
- includes/RequestWiki/Handler/RestWikiRequestsByUser.php
- includes/RequestWiki/SpecialRequestWiki.php
- includes/RequestWiki/SpecialRequestWikiQueue.php
- includes/RestUtils.php
- tests/phpunit/SpecialRequestWikiTest.php
https://issue-tracker.miraheze.org/T12011
> T12011: Disable the special pages and API outside of the global wiki

- i18n/en.json
- i18n/qqq.json
- includes/RestUtils.php
- tests/phpunit/SpecialRequestWikiTest.php
Missed it on my previous PR (https://github.com/miraheze/CreateWiki/pull/519)
> T12011: Add missing i18n and fix CI

- i18n/en.json
Reverts miraheze/CreateWiki#514
> Revert "Remove colon from the database name header"

- includes/RequestWiki/RequestWikiRequestViewer.php
- includes/RequestWiki/WikiRequest.php
This change will make the type of the visibility property consistent at all times.
> Make the `visibility` property private

- includes/RequestWiki/WikiRequest.php
- includes/WikiManager.php
- tests/phpunit/RemoteWikiTest.php
- tests/phpunit/WikiManagerTest.php
Reverts miraheze/CreateWiki#485
> Revert "Migrate to use InsertQueryBuilder"

- includes/CreateWikiPhp.php
> Write out to temporary file and move it

- includes/WikiManager.php
Prevent list from updating twice immediately.
> Don't call ->update if we regenerate lists

- includes/Jobs/CreateWikiJob.php
- includes/Jobs/RequestWikiAIJob.php
- includes/RequestWiki/Handler/RestWikiRequestComment.php
- includes/RequestWiki/RequestWikiRequestViewer.php
- includes/Services/WikiRequestManager.php
This restores prior notifications behavior, before #567
> Fix notifications (T12726)

- includes/Hooks/Handlers/Main.php
- includes/Services/CreateWikiDataFactory.php
We also do in CreateWikiDataFactory as that is ran in SetupAfterCache as well.
> Avoid file_exists check in SetupAfterCache

- extension.json
- i18n/en.json
- i18n/qqq.json
- includes/ConfigNames.php
- includes/RequestWiki/SpecialRequestWiki.php
This will either be moved to WikiDiscover or MirahezeMagic via hooks
> Remove public-description

- extension.json
- includes/CreateWiki/SpecialCreateWiki.php
- includes/RequestWiki/RequestWikiRequestViewer.php
- includes/RequestWiki/SpecialRequestWiki.php
- includes/RequestWiki/SpecialRequestWikiQueue.php
- includes/Services/WikiRequestManager.php
- modules/ext.createwiki.oouiform.ooui.less
This also fixes a bug with saving some extra field data
> Redesign RequestWikiQueue

- includes/RequestWiki/FormFields/DetailsWithIconField.php
- includes/RequestWiki/RequestWikiRequestViewer.php
Will complete [T12760](https://issue-tracker.wikitide.org/T12760)
> Add DetailsWithIconField

- extension.json
- i18n/qqq.json
- includes/ConfigNames.php
- includes/RestUtils.php
To me, it makes more sense to enable something than to disable it with config.
> Repurpose DisableRESTAPI as EnableRESTAPI

- CreateWikiMagic.php
- includes/Hooks/Handlers/Main.php
Reverts miraheze/CreateWiki#612
> Revert "add NUMBEROFOPENREQUESTS magicword"

- CreateWikiMagic.php
- includes/Hooks/Handlers/Main.php
Reverts miraheze/CreateWiki#618
> Revert "Revert "add NUMBEROFOPENREQUESTS magicword""

- includes/Services/WikiManagerFactory.php
- tests/phpunit/Services/WikiManagerFactoryTest.php
Also has a minor performance boost since it removes one query that we no longer need.
> Don't fail if cluster is empty

- includes/Services/WikiManagerFactory.php
> Convert doCreateDatabase to a public function

- includes/Jobs/RequestWikiRemoteAIJob.php
It looks for $this->reason which no longer exists
> Fix canAutoApprove()

- includes/Jobs/RequestWikiRemoteAIJob.php
- includes/Services/WikiRequestManager.php
> Remove getRequesterUsername

- includes/RequestWiki/Specials/SpecialRequestWiki.php
- includes/Services/CreateWikiValidator.php
- includes/Services/WikiRequestViewer.php
- tests/phpunit/RequestWiki/Specials/SpecialRequestWikiTest.php
- tests/phpunit/Services/CreateWikiValidatorTest.php
Also fixes some other CreateWikiValidator tests and expands SpecialRequestWiki tests.
> Move some things to CreateWikiValidator

- includes/Services/RemoteWikiFactory.php
Reverts miraheze/CreateWiki#630
> Revert "RemoteWikiFactory: fix overriding assignment"

- includes/Services/RemoteWikiFactory.php
Reverts miraheze/CreateWiki#700
> Revert "Revert "RemoteWikiFactory: fix overriding assignment""

- includes/Services/RemoteWikiFactory.php
> Remove addNewRow

- extension.json
Also cleans up a few other config descriptions.
> Update description for the CreateWikiDatabaseClusters config

- sql/cw_requests.sql
- sql/cw_wikis.sql
- sql/patches/patch-cw_requests-add-cw_extra.sql
- sql/patches/patch-cw_wikis-add-wiki_extra.sql
Technically this is just an alias to LONGTEXT but it also adds a constraint ensuring valid JSON
> Use JSON datatype for JSON fields
